Update navbar-icon css
firstcontributions/firstcontributions.github.io pull request #149
Opened 2020-10-04 13:52 UTC by uzzii-21

2020-11-09 04:51 UTC, kevinnls commented on src/components/Navbar/Navbar.css
> +    background: #33ade84f;
a little bit more white?

2020-11-09 05:09 UTC, kevinnls requested changes

2020-11-09 05:09 UTC, kevinnls commented on src/components/Navbar/Navbar.css
> +    background: #33ade84f;
maybe `#c1e0ef4f` ? i think that would look nice

2020-12-12 16:23 UTC, gabrielsanttana commented on src/components/Navbar/Navbar.css
> +    margin: 10px 0;
Applying the margin this way would also add `10px` of `margin-bottom`. Is that the intention or you just would like the minify it with `margin: 10px 0 0;`

2025-09-30 21:21 UTC, closed without merging