Update listOfProjects.js
firstcontributions/firstcontributions.github.io pull request #155
Opened 2020-10-19 08:14 UTC by Summer-source

2020-11-09 04:31 UTC, kevinnls requested changes
i'm not sure about including this project. they don't have any issues labelled as `good first issue`. @Roshanjossey ?

as for the PR itself, i was initially quite confused but towards the end i think i understand you've copied the entry for a different project, but not changed all the values as required. so please make those changes

2020-11-09 04:31 UTC, kevinnls commented on src/components/ProjectList/listOfProjects.js
> +    githubLink:
```suggestion
   projectLink:

```

2020-11-09 04:31 UTC, kevinnls commented on src/components/ProjectList/listOfProjects.js
> +      'https:github.com/ValveSoftware/Proton.git',
```suggestion
      'https://github.com/ValveSoftware/Proton',
```

2020-11-09 04:31 UTC, kevinnls commented on src/components/ProjectList/listOfProjects.js
> +    description: 'A keyboard-driven, vim-like browser based on PyQt5',
this does not seem to describe your linked project in any way :thinking: 

could you please check the link?

2020-11-09 04:31 UTC, kevinnls commented on src/components/ProjectList/listOfProjects.js
> +    tags: ['Python','Qt','windows','gamer','streamplay','qtWebEngine','app']
i'm assuming from the link that you meant `SteamPlay` but again the other tags don't match the linked repo. there is only little Python and no Qt on Proton (as far as i can see)

2020-11-09 04:31 UTC, kevinnls commented on src/components/ProjectList/listOfProjects.js
> +    imageSrc: 'https://avatars1.githubusercontent.com/u/21955151?s=200&v=4',
that is qutebrowser's image. please change to Proton's logo

2021-01-03 11:27 UTC, sara-02 commented
@Summer-source Can you please look into the comments? Thanks

2021-01-04 05:26 UTC, kevinnls commented
@Summer-source your PR has gained a lot of merge conflicts now; and the listing you added was mix-and-match. please provide the right details:
```js
{
    name: /*ITEM NAME*/,
    imageSrc: /*LINK TO ICON*/,
    projectLink: /*LINK TO PROJ GOOD FIRST ISSUES*/,
    description: /*DESCRIBE PROJ*/,
    tags: [/*tags*/, /*as*/, /*string*/, /*array*/]
  },
```
replace all the `/**/` comments with the right `'string values'`

i would recommend opening a fresh PR after syncing your fork with `source`

2021-01-04 05:37 UTC, closed without merging

2021-01-04 08:17 UTC, Summer-source commented
@kevinnls you can delete my pr . Thank You

2021-01-04 08:23 UTC, kevinnls commented
have you opened a new one @Summer-source ?
please mention the new PR number

2021-01-04 08:26 UTC, Summer-source commented
No i havent @kevinnls