Update listOfProjects.js
firstcontributions/firstcontributions.github.io pull request #276
Opened 2022-10-19 17:45 UTC by lemostrash

- Interactive content in Go language

2022-10-20 10:06 UTC, Roshanjossey requested changes
Just one syntax correction.

All the best for this project. I'm a big fan of exercism and learning language through TDD. I hope this project works well.

2022-10-20 10:06 UTC, Roshanjossey commented on src/components/ProjectList/listOfProjects.js
>    }
```suggestion
  },
```

2022-10-21 06:03 UTC, merged

2022-10-21 06:03 UTC, Roshanjossey commented
Thank you for making this change 🖖 ✨

2022-10-21 11:30 UTC, lemostrash commented
Thanks for the opportunity.